### PR TITLE
Added support for Pop!_OS 20.04

### PR DESCRIPTION
**Pull request by MatrixDJ96**

### CODE REVIEW

**Comment by kazik56** [comment]
To make it compatible with Pop!_OS 20.10 change `focal` to `groovy` in line 13.

**Comment by thiggy01** [comment]
I'm going to add support for Pop OS 20.04 and 20.10. Stay tuned.

**Review by thiggy01 — COMMENTED** [review]
I liked your code, but I have to make adjustments to make it more readable and adaptable to other distros.

**Comment by thiggy01** [comment]
Pop OS support added.

**Comment by MatrixDJ96** [comment]
I feel it like a merged pull request, thank @thiggy01

**Pull request closed without merging**
